name:deploy to azure 

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build --prod

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server:  'ftps://waws-prod-dxb-007.ftp.azurewebsites.windows.net/site/wwwroot '
          username:  'megaclaim__test\$megaclaim__test '
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist//test-app/
          remote-dir: /site/wwwroot/
